# Exportar modelo a un fichero
Una vez que hemos entrenado nuestro modelo, podemos guardarlo en un fichero binario (mediante la librería pickle) para poder llevarlo a otro entorno o programa.

Pasos:

1.- Importamos la librería pickle

import pickle

2.- Creamos un fichero binario (modelo_entrenado.pickle) con el modelo entrenado

with open("modelo_entrenado.pickle", "wb") as file:
    pickle.dump(modelo_entrenado, file)


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [2]:
flores=sns.load_dataset('iris')
y=flores['species']
X=flores.drop('species',axis=1)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)
modelo=SVC(gamma='auto')
modelo.fit(X_train,y_train)
predicciones=modelo.predict(X_test)

from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,predicciones))
print(confusion_matrix(y_test,predicciones))


              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.94      0.94      0.94        18
   virginica       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[12  0  0]
 [ 0 17  1]
 [ 0  1 14]]


In [3]:
import pickle

In [4]:
with open("modelo.pickle","wb") as file:
    pickle.dump(modelo,file)

# Importar modelo desde un fichero
Si queremos importar un modelo de machine learning ya entrenado que está grabado en un fichero binario, seguiremos estos pasos:

1.- Importamos la librería pickle

import pickle

2.- Importamos el modelo desde el fichero binario "modelo_entrenado.pickle"

with open('modelo_entrenado.pickle', "rb") as file:
    modelo_entrenado = pickle.load(file)

In [6]:
with open('modelo.pickle','rb') as file:
    modelo2=pickle.load(file)

In [7]:
predicciones=modelo2.predict(X_test)

print(classification_report(y_test,predicciones))
print(confusion_matrix(y_test,predicciones))


              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.94      0.94      0.94        18
   virginica       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[12  0  0]
 [ 0 17  1]
 [ 0  1 14]]
